### ISSUE TITLE
Build fails on "@ada/infra" step in Version 1.2.0 

### ISSUE THREAD

**Issue by rishidjh** [aws-solutions/automated-data-analytics-on-aws#56]
**Describe the bug**
I want to customize the front end of the solution, hence trying to setup this solution using the github repo and following the README file steps, rather than CFT template way.
I am using EC2 linux machine (tried with Ubuntu too) for this setup, however it keeps on failing at "@ada/infra" step.
_UnrecognizedClientException: The Access Key ID or security token is invalid._
I have aws credentials configured on the EC2 box using aws configure. I would expect the project to read the credentials from there since credentials are not supplied explicitly in any steps in the documentation.

**To Reproduce**
Follow all the steps given in README.md file at the root of the project
run the script file "./run-all-tests.sh"

**Expected behavior**
Build should complete successfully

**Please complete the following information about the solution:**
- [x] Version: v1.2.0

```

- [ ] Region: [e.g. ap-southeast-1]
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes, all good
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
<img width="998" alt="Screenshot 2023-09-04 at 7 21 29 PM" src="https://github.com/aws-solutions/automated-data-analytics-on-aws/assets/70216164/0b7382a7-709f-415c-ad0c-d9040f47d3ff">


**Additional context**
Is there any other way to make this solution work on local system so that I can customize the website (front end)?

**Comment by dougtoppin** [comment]
@rishidjh thanks for your report, sorry about the delayed response, we will investigate and get back to you

**Comment by dougtoppin** [comment]
@rishidjh Is this still an issue for you? If you set your credentials into the shell environment does this work?

**Comment by dougtoppin** [comment]
closing this issue, if there are still any problem, please confirm that the latest release is being used and create a new issue
