### ISSUE TITLE
Build fails on "@ada/api"

### ISSUE THREAD

**Issue by aniket-zeroandone** [aws-solutions/automated-data-analytics-on-aws#58]
**Describe the bug**
So the issue is 

@ada/api: $ yarn clean && yarn generate
@ada/api: $ rm -rf build client docs
@ada/api: $ yarn generate:openapi
@ada/api: $ ts-node -C ttypescript ./generators/openapi/generate.ts
@ada/api: /home/ec2-user/automated-data-analytics-on-aws/source/node_modules/ttypescript/lib/loadTypescript.js:13
@ada/api:         function __() { this.constructor = d; }
@ada/api:                                          ^
@ada/api: TypeError: Cannot set property constructor of [object Object] which has only a getter
@ada/api:     at new __ (/home/ec2-user/automated-data-analytics-on-aws/source/node_modules/ttypescript/lib/loadTypescript.js:13:42)
@ada/api:     at __extends (/home/ec2-user/automated-data-analytics-on-aws/source/node_modules/ttypescript/lib/loadTypescript.js:14:84)
@ada/api:     at /home/ec2-user/automated-data-analytics-on-aws/source/node_modules/ttypescript/lib/loadTypescript.js:65:5
@ada/api:     at Object.<anonymous> (/home/ec2-user/automated-data-analytics-on-aws/source/node_modules/ttypescript/lib/loadTypescript.js:100:2)
@ada/api:     at Module._compile (node:internal/modules/cjs/loader:1198:14)
@ada/api:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
@ada/api:     at Module.load (node:internal/modules/cjs/loader:1076:32)
@ada/api:     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
@ada/api:     at Module.require (node:internal/modules/cjs/loader:1100:19)
@ada/api:     at require (node:internal/modules/cjs/helpers:119:18)
@ada/api: error Command failed with exit code 1.
@ada/api: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@ada/api: error Command failed with exit code 1.
@ada/api: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@ada/api: error Command failed with exit code 1.
@ada/api: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in '@ada/api'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**To Reproduce**
After all prerequisites done trying to Build and run unit test in that this issue is coming for @ada/api package.

**Comment by makawtharani** [comment]
++

**Comment by zilurrane** [comment]
@rashimr @johnrichter-aws @swap-aws - Any help?

**Comment by aniket-zeroandone** [comment]
@zilurrane 
Thanks this resolved my issue.
