### ISSUE TITLE
CREATE_FAILED : You don't have the permissions that are required to perform this operation on AthenaProxyCloudFrontWebAclPutLoggingConfiguration.

### ISSUE THREAD

**Issue by aniket-zeroandone** [aws-solutions/automated-data-analytics-on-aws#67]
**Describe the bug**
CREATE_FAILED : You don't have the permissions that are required to perform this operation on AthenaProxyCloudFrontWebAclPutLoggingConfiguration. 

Despite the fact that I have granted IAM Role Administrator access to both Instance and CloudFormation/CloudFront.

**Comment by dougtoppin** [comment]
@aniket-zeroandone thanks for your report, we will investigate and get back to you

**Comment by dougtoppin** [comment]
@aniket-zeroandone Are you still having any issue with this? I could not duplicate the issue using the v1.4.0 release with an ec2 that has an admin role attached to it.
