### ISSUE TITLE
Build fails on docker container

### ISSUE THREAD

**Issue by joseaparicioquake** [aws-solutions/automated-data-analytics-on-aws#68]
**Describe the bug**
I want to customize the way the solution creates connections to the RDS with glue, using connectors with our transit gateway, trying to setup this solution using the github repo and following the README file steps, rather than CFT template way.
I am using EC2 linux machine with Ubuntu as recommended per documentation for this setup, however it is appearing an error related to docker containers that I´m unable to solve.

> $ docker run -v $(pwd)/../../../:/source -v $HOME/.m2:/root/.m2 -w /source ada-java-build-base scripts/build-java.sh athena-lens install
> Unable to find image 'ada-java-build-base:latest' locally
> docker: Error response from daemon: pull access denied for ada-java-build-base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
> See 'docker run --help'.

**To Reproduce**
Follow all the steps given in README.md file at the root of the project
Use an EC2 with Ubuntu as SO, on an public subnet with IGW
run the script file "./run-all-tests.sh"

**Expected behavior**
Build should complete successfully

**Please complete the following information about the solution:**

- [x] Version: [e.g. v1.3.0]

- [x] Region: [us-east-1]
- [] Was the solution modified from the version published on this repository?
- [] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?[Yes]
- [x] Were there any errors in the CloudWatch Logs?[No]

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
![image](https://github.com/aws-solutions/automated-data-analytics-on-aws/assets/148251545/a030b3b8-24fd-446a-ba58-4af84cb5fbd6)

**Additional context**

**Comment by dougtoppin** [comment]
@joseaparicioquake thanks for your report, we will investigate and get back to you

**Comment by dougtoppin** [comment]
@joseaparicioquake Rather than the top level run-all-tests.sh, try going to the readme in the source directory and doing *yarn install* ?

That may create the ada-java-build-base image.

**Comment by joseaparicioquake** [comment]
Hi @dougtoppin, I´m closing this thread. I´ve discovered the reason behind this error.
For anyone with this kind of error, make sure to use ./run-all-tests.sh. with all dependencies installed
